### ISSUE TITLE
even smaller browser module

### ISSUE THREAD

**Issue by focusaurus** [hughsk/btoa-lite#1]
I think just `module.exports = btoa` (or `window.btoa` if you want to be a bit more explicit) will get it done for browser support. Here's a very similar reference file from [form-data](https://github.com/form-data/form-data/blob/master/lib/browser.js).

**Comment by hughsk** [comment]
`module.exports = btoa` results in an invocation error in the browser given that it's not called directly from `window` :') Thanks for reporting though!

<img width="315" alt="screen shot 2016-03-27 at 4 35 44 pm" src="https://cloud.githubusercontent.com/assets/569817/14063998/02d3f014-f43a-11e5-83fa-2721559d2688.png">
